[package]
name = "iiif-tiler-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
derive = "1.0.0"
features = "0.10.0"
image = "0.25.5"
serde = "1.0.215"
serde_json = {version = "1.0.133", features = ["preserve_order"]}
